
export const bug_sample_data = {
  query: "crash",
  limit: 25,
  bugs: [
    {
      bug_id: "1873874",
      title:
        "Crash [@ mozilla::net::Predictor::Action::OnCacheEntryAvailable] via IPC method NeckoParent::RecvPredPredict",
      description:
        "net predictor action oncacheentryavailable via ipc method neckoparent recvpredpredict",
      status: "RESOLVED",
      created_at: "2024-01-10T10:50:28Z",
      score: 1,
    },
    {
      bug_id: "1873801",
      title: "Crash in [@ mozilla::WebrtcVideoConduit::OnControlConfigChange]",
      description: "webrtcvideoconduit oncontrolconfigchange",
      status: "RESOLVED",
      created_at: "2024-01-10T00:41:10Z",
      score: 1,
    },
    {
      bug_id: "1873790",
      title:
        "Hit MOZ_CRASH(CanvasChild not thread-safe) at /builds/worker/checkouts/gecko/xpcom/base/nsISupportsImpl.cpp:43",
      description: "hit moz_crash canvaschild thread-safe",
      status: "RESOLVED",
      created_at: "2024-01-09T23:43:30Z",
      score: 1,
    },
    {
      bug_id: "1873701",
      title: "Crash in [@ SkGradientShaderBase::SkGradientShaderBase]",
      description: "skgradientshaderbase skgradientshaderbase",
      status: "RESOLVED",
      created_at: "2024-01-09T17:33:31Z",
      score: 1,
    },
    {
      bug_id: "1873661",
      title: "Crash in automation when someone misuses instrumentation APIs",
      description: "automation someone misuses instrumentation apis",
      status: "RESOLVED",
      created_at: "2024-01-09T14:26:09Z",
      score: 1,
    },
    {
      bug_id: "1873597",
      title: "Crash in [@ memchr] in nsContentUtils::IsURIInList()",
      description: "memchr nscontentutils isuriinlist",
      status: "RESOLVED",
      created_at: "2024-01-09T06:17:55Z",
      score: 1,
    },
    {
      bug_id: "1873577",
      title: "Double-free crashes from CTFontEntry::HasFontTable()",
      description: "double-free crashes ctfontentry hasfonttable",
      status: "RESOLVED",
      created_at: "2024-01-09T01:16:05Z",
      score: 1,
    },
    {
      bug_id: "1873573",
      title:
        "crash near null in [@ mozilla::dom::(anonymous namespace)::PermissionResultRunnable::WorkerRun()]",
      description:
        "near null dom anonymous namespace permissionresultrunnable workerrun",
      status: "VERIFIED",
      created_at: "2024-01-09T00:42:13Z",
      score: 1,
    },
    {
      bug_id: "1873462",
      title:
        "Intermittent application crashed [@ mozilla::WMFMediaDataEncoder::ConvertToNV12InputSample] | single tracking bug",
      description:
        "intermittent application crashed wmfmediadataencoder converttonv12inputsample single tracking",
      status: "RESOLVED",
      created_at: "2024-01-08T14:01:26Z",
      score: 1,
    },
    {
      bug_id: "1873229",
      title: "Crash [@ LateWriteObserver::Observe]",
      description: "latewriteobserver observe",
      status: "VERIFIED",
      created_at: "2024-01-05T16:18:15Z",
      score: 1,
    },
    {
      bug_id: "1873210",
      title: "Support langpacks in the crash reporter",
      description: "support langpacks reporter",
      status: "VERIFIED",
      created_at: "2024-01-05T14:32:12Z",
      score: 1,
    },
    {
      bug_id: "1873047",
      title:
        "AddressSanitizer: breakpoint on unknown address 0x7ffd1a1620b2 [@ AnnotateMozCrashReason]",
      description:
        "addresssanitizer breakpoint unknown address annotatemozcrashreason",
      status: "RESOLVED",
      created_at: "2024-01-04T16:16:21Z",
      score: 1,
    },
    {
      bug_id: "1872966",
      title:
        "Intermittent application crashed [@ MozJemallocPHC::malloc] | single tracking bug",
      description:
        "intermittent application crashed mozjemallocphc malloc single tracking",
      status: "RESOLVED",
      created_at: "2024-01-04T03:19:18Z",
      score: 1,
    },
    {
      bug_id: "1872960",
      title:
        "Hit MOZ_CRASH(Quota manager shutdown timed out) at /builds/worker/checkouts/gecko/dom/quota/ActorsParent.cpp:2273",
      description: "hit moz_crash quota manager shutdown timed",
      status: "RESOLVED",
      created_at: "2024-01-04T01:50:37Z",
      score: 1,
    },
    {
      bug_id: "1872956",
      title:
        "Crash in [@ OOM | large | NS_ABORT_OOM | nsTSubstring<T>::AllocFailed | CopyUTF8toUTF16 | mozilla::dom::Document::GetDocumentURI]",
      description:
        "oom large ns_abort_oom nstsubstring allocfailed copyutf8toutf16 dom document getdocumenturi",
      status: "RESOLVED",
      created_at: "2024-01-04T01:02:44Z",
      score: 1,
    },
    {
      bug_id: "1872834",
      title: "Crash [@ mozilla::dom::FilePickerParent::RecvClose]",
      description: "dom filepickerparent recvclose",
      status: "RESOLVED",
      created_at: "2024-01-03T10:49:18Z",
      score: 1,
    },
    {
      bug_id: "1872744",
      title:
        "Crash in [@ mozilla::net::DNSRequestSender::Cancel::$::operator()] on poison value",
      description: "net dnsrequestsender cancel operator poison value",
      status: "RESOLVED",
      created_at: "2024-01-02T20:43:57Z",
      score: 1,
    },
  ],
  developers: [
    {
      developer_id: "omansfeld@mozilla.com",
      name: "omansfeld@mozilla.com",
      email: "omansfeld@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873874"],
    },
    {
      developer_id: "docfaraday@gmail.com",
      name: "docfaraday@gmail.com",
      email: "docfaraday@gmail.com",
      total_fixed_bugs: null,
      bug_ids: ["1873801"],
    },
    {
      developer_id: "aosmond@mozilla.com",
      name: "aosmond@mozilla.com",
      email: "aosmond@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1872956", "1873701", "1873790"],
    },
    {
      developer_id: "pmcmanis@mozilla.com",
      name: "pmcmanis@mozilla.com",
      email: "pmcmanis@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873661"],
    },
    {
      developer_id: "bvandersloot@mozilla.com",
      name: "bvandersloot@mozilla.com",
      email: "bvandersloot@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873597"],
    },
    {
      developer_id: "jfkthame@gmail.com",
      name: "jfkthame@gmail.com",
      email: "jfkthame@gmail.com",
      total_fixed_bugs: null,
      bug_ids: ["1873577"],
    },
    {
      developer_id: "echuang@mozilla.com",
      name: "echuang@mozilla.com",
      email: "echuang@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873573"],
    },
    {
      developer_id: "aryx.bugmail@gmx-topmail.de",
      name: "aryx.bugmail@gmx-topmail.de",
      email: "aryx.bugmail@gmx-topmail.de",
      total_fixed_bugs: null,
      bug_ids: ["1873462"],
    },
    {
      developer_id: "krosylight@mozilla.com",
      name: "krosylight@mozilla.com",
      email: "krosylight@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873229"],
    },
    {
      developer_id: "afranchuk@mozilla.com",
      name: "afranchuk@mozilla.com",
      email: "afranchuk@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1873210"],
    },
    {
      developer_id: "nical.bugzilla@gmail.com",
      name: "nical.bugzilla@gmail.com",
      email: "nical.bugzilla@gmail.com",
      total_fixed_bugs: null,
      bug_ids: ["1873047"],
    },
    {
      developer_id: "nobody@mozilla.org",
      name: "nobody@mozilla.org",
      email: "nobody@mozilla.org",
      total_fixed_bugs: null,
      bug_ids: ["1872960", "1872966"],
    },
    {
      developer_id: "choller@mozilla.com",
      name: "choller@mozilla.com",
      email: "choller@mozilla.com",
      total_fixed_bugs: null,
      bug_ids: ["1872834"],
    },
    {
      developer_id: "rjesup@jesup.org",
      name: "rjesup@jesup.org",
      email: "rjesup@jesup.org",
      total_fixed_bugs: null,
      bug_ids: ["1872744"],
    },
  ],
  commits: [
    {
      commit_id: "1873874_0",
      hash: "1873874_0",
      message:
        "Fixed crash due to empty mTargetURI when calling Predictor::Action::OnCacheEntryAvailable, r=#necko",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/0c8035cc5a84",
      committed_at: null,
      bug_ids: ["1873874"],
    },
    {
      commit_id: "1873874_1",
      hash: "1873874_1",
      message:
        "Fixed crash due to empty mTargetURI when calling Predictor::Action::OnCacheEntryAvailable, r=necko-reviewers,kershaw",
      repository: "https://hg.mozilla.org/mozilla-central/rev/0c8035cc5a84",
      committed_at: null,
      bug_ids: ["1873874"],
    },
    {
      commit_id: "1873874_2",
      hash: "1873874_2",
      message: "Pushed by kjang@mozilla.com:",
      repository: null,
      committed_at: null,
      bug_ids: ["1873874"],
    },
    {
      commit_id: "1873801_0",
      hash: "1873801_0",
      message:
        "Make sure pseudo codecs are after real codecs in priority order. r=mjf",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/33f90f00e8e9",
      committed_at: null,
      bug_ids: ["1873801"],
    },
    {
      commit_id: "1873801_1",
      hash: "1873801_1",
      message:
        "Make sure pseudo codecs are after real codecs in priority order. r?mjf",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/37e780bf8eff",
      committed_at: null,
      bug_ids: ["1873801"],
    },
    {
      commit_id: "1873801_2",
      hash: "1873801_2",
      message: "Pushed by bcampen@mozilla.com:",
      repository: "https://hg.mozilla.org/mozilla-central/rev/33f90f00e8e9",
      committed_at: null,
      bug_ids: ["1873801"],
    },
    {
      commit_id: "1873801_3",
      hash: "1873801_3",
      message: "Test cases for bug. r=mjf",
      repository: "https://hg.mozilla.org/mozilla-central/rev/37e780bf8eff",
      committed_at: null,
      bug_ids: ["1873801"],
    },
    {
      commit_id: "1873801_4",
      hash: "1873801_4",
      message: "Test cases for bug. r?mjf",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/d2989996f577",
      committed_at: null,
      bug_ids: ["1873801"],
    },
    {
      commit_id: "1873790_0",
      hash: "1873790_0",
      message:
        "Ensure that we release CanvasChild::DataShmemHolder on main thread.",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/7a07cd281802",
      committed_at: null,
      bug_ids: ["1873790"],
    },
    {
      commit_id: "1873790_1",
      hash: "1873790_1",
      message:
        "Ensure that we release CanvasChild::DataShmemHolder on main thread. r=gfx-reviewers,lsalzman",
      repository: "https://hg.mozilla.org/mozilla-central/rev/7a07cd281802",
      committed_at: null,
      bug_ids: ["1873790"],
    },
    {
      commit_id: "1873790_2",
      hash: "1873790_2",
      message: "Pushed by aosmond@mozilla.com:",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/44093ca559de",
      committed_at: null,
      bug_ids: ["1873790"],
    },
    {
      commit_id: "1873701_0",
      hash: "1873701_0",
      message: "Pushed by aosmond@mozilla.com:",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/33d47d05c368",
      committed_at: null,
      bug_ids: ["1873701"],
    },
    {
      commit_id: "1873701_1",
      hash: "1873701_1",
      message: "r=gfx-reviewers,lsalzman",
      repository: "https://hg.mozilla.org/mozilla-central/rev/33d47d05c368",
      committed_at: null,
      bug_ids: ["1873701"],
    },
    {
      commit_id: "1873661_0",
      hash: "1873661_0",
      message:
        "Crash in automation when someone misuses instrumentation APIs r=chutten",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/b77f0844ff57",
      committed_at: null,
      bug_ids: ["1873661"],
    },
    {
      commit_id: "1873661_1",
      hash: "1873661_1",
      message:
        "Crash in automation when someone misuses instrumentation APIs r=chutten!",
      repository: "https://hg.mozilla.org/mozilla-central/rev/b77f0844ff57",
      committed_at: null,
      bug_ids: ["1873661"],
    },
    {
      commit_id: "1873661_2",
      hash: "1873661_2",
      message: "Pushed by pmcmanis@mozilla.com:",
      repository: null,
      committed_at: null,
      bug_ids: ["1873661"],
    },
    {
      commit_id: "1873597_0",
      hash: "1873597_0",
      message:
        "Improve URI-list matching algorithm for performance - r=nika!,#anti-tracking!",
      repository: "https://hg.mozilla.org/mozilla-central/rev/d8e90bb252ae",
      committed_at: null,
      bug_ids: ["1873597"],
    },
    {
      commit_id: "1873577_0",
      hash: "1873577_0",
      message: "Improve locking in CTFontEntry. r=#gfx-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/0dd14ea2334a",
      committed_at: null,
      bug_ids: ["1873577"],
    },
    {
      commit_id: "1873577_1",
      hash: "1873577_1",
      message: "Improve locking in CTFontEntry. r=gfx-reviewers,lsalzman",
      repository: "https://hg.mozilla.org/mozilla-central/rev/0dd14ea2334a",
      committed_at: null,
      bug_ids: ["1873577"],
    },
    {
      commit_id: "1873577_2",
      hash: "1873577_2",
      message: "Pushed by jkew@mozilla.com:",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/0caf7b959d3a",
      committed_at: null,
      bug_ids: ["1873577"],
    },
    {
      commit_id: "1873577_3",
      hash: "1873577_3",
      message: "[esr115] Improve locking in MacOSFontEntry. r=#gfx-reviewers",
      repository:
        "https://hg.mozilla.org/releases/mozilla-esr115/rev/74bbb12fa455",
      committed_at: null,
      bug_ids: ["1873577"],
    },
    {
      commit_id: "1873573_0",
      hash: "1873573_0",
      message: "Pushed by echuang@mozilla.com:",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/a8c5441fd896",
      committed_at: null,
      bug_ids: ["1873573"],
    },
    {
      commit_id: "1873573_1",
      hash: "1873573_1",
      message:
        "Rename PromiseWorkerProxy::WorkerPromise() to GetWorkerPromise(). r=#dom-worker-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/a8c5441fd896",
      committed_at: null,
      bug_ids: ["1873573"],
    },
    {
      commit_id: "1873573_2",
      hash: "1873573_2",
      message:
        "Rename PromiseWorkerProxy::WorkerPromise() to GetWorkerPromise(). r=dom-worker-reviewers,smaug",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/828272c42368",
      committed_at: null,
      bug_ids: ["1873573"],
    },
    {
      commit_id: "1873462_0",
      hash: "1873462_0",
      message: "(In reply to Pulsebot from comment #14)",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/25cede034a0c",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_1",
      hash: "1873462_1",
      message: "> Pushed by archaeopteryx@coole-files.de:",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/39923856fd4e",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_2",
      hash: "1873462_2",
      message: "> disabled all *_444_* tests in full-cycle-test",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/5f5966a0851e",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_3",
      hash: "1873462_3",
      message: "Pushed by archaeopteryx@coole-files.de:",
      repository: "https://hg.mozilla.org/mozilla-central/rev/25cede034a0c",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_4",
      hash: "1873462_4",
      message: "Pushed by ncsoregi@mozilla.com:",
      repository: "https://hg.mozilla.org/mozilla-central/rev/39923856fd4e",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_5",
      hash: "1873462_5",
      message: "disabled all *_444_* tests in full-cycle-test",
      repository: "https://hg.mozilla.org/mozilla-central/rev/5f5966a0851e",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_6",
      hash: "1873462_6",
      message:
        "set webcodec's full-cycle-test's vp9 tests video-encoder as precondition failed on Windows",
      repository: "https://hg.mozilla.org/mozilla-central/rev/809daea6181a",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873462_7",
      hash: "1873462_7",
      message:
        "update expectation for webcodecs/full-cycle-test.https.any.worker.html to account for crashes on Windows Code Coverage",
      repository: "https://hg.mozilla.org/mozilla-central/rev/d78078443b2c",
      committed_at: null,
      bug_ids: ["1873462"],
    },
    {
      commit_id: "1873229_0",
      hash: "1873229_0",
      message: "Add a shutdown blocker for NotificationDB r=asuth",
      repository: "93db8f4d488c",
      committed_at: null,
      bug_ids: ["1873229"],
    },
    {
      commit_id: "1873229_1",
      hash: "1873229_1",
      message: "Add a shutdown blocker for NotificationDB r=asuth,jstutte",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/306a8e5f5de0",
      committed_at: null,
      bug_ids: ["1873229"],
    },
    {
      commit_id: "1873229_2",
      hash: "1873229_2",
      message:
        "Initial support for NVIDIA RTX Video Super Resolution r=gfx-reviewers,sotaro",
      repository: "https://hg.mozilla.org/mozilla-central/rev/306a8e5f5de0",
      committed_at: null,
      bug_ids: ["1873229"],
    },
    {
      commit_id: "1873229_3",
      hash: "1873229_3",
      message: "Pushed by krosylight@mozilla.com:",
      repository: null,
      committed_at: null,
      bug_ids: ["1873229"],
    },
    {
      commit_id: "1873210_0",
      hash: "1873210_0",
      message: "Pushed by afranchuk@mozilla.com:",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/adb24ac8e58e",
      committed_at: null,
      bug_ids: ["1873210"],
    },
    {
      commit_id: "1873210_1",
      hash: "1873210_1",
      message: "Support langpacks in the crashreporter client",
      repository: "https://hg.mozilla.org/mozilla-central/rev/adb24ac8e58e",
      committed_at: null,
      bug_ids: ["1873210"],
    },
    {
      commit_id: "1873210_2",
      hash: "1873210_2",
      message: "Support langpacks in the crashreporter client r=gsvelto",
      repository:
        "https://hg.mozilla.org/releases/mozilla-esr128/rev/c56c9353b98a",
      committed_at: null,
      bug_ids: ["1873210"],
    },
    {
      commit_id: "1873210_3",
      hash: "1873210_3",
      message:
        "Support langpacks in the crashreporter client r=gsvelto,supply-chain-reviewers",
      repository: null,
      committed_at: null,
      bug_ids: ["1873210"],
    },
    {
      commit_id: "1873047_0",
      hash: "1873047_0",
      message:
        "Generate a valid BindGroup object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/055f1bcf0675",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_1",
      hash: "1873047_1",
      message:
        "Generate a valid BindGroup object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/2a1661674e34",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_2",
      hash: "1873047_2",
      message:
        "Generate a valid BindGroupLayout object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/30b515db994b",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_3",
      hash: "1873047_3",
      message:
        "Generate a valid BindGroupLayout object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/6a97aed289ab",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_4",
      hash: "1873047_4",
      message:
        "Generate a valid CommandEncoder object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/7142405fee57",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_5",
      hash: "1873047_5",
      message:
        "Generate a valid CommandEncoder object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/79282fd571c5",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_6",
      hash: "1873047_6",
      message:
        "Generate a valid ComputePipeline object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/8f0c15267535",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_7",
      hash: "1873047_7",
      message:
        "Generate a valid ComputePipeline object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/aca3db8439db",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_8",
      hash: "1873047_8",
      message:
        "Generate a valid PipelineLayout object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/bba7b8f2946f",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_9",
      hash: "1873047_9",
      message:
        "Generate a valid PipelineLayout object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/bc67106c19d8",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_10",
      hash: "1873047_10",
      message:
        "Generate a valid RenderPipeline object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/d0475e27ae48",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_11",
      hash: "1873047_11",
      message:
        "Generate a valid RenderPipeline object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/055f1bcf0675",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_12",
      hash: "1873047_12",
      message:
        "Generate a valid Sampler object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/2a1661674e34",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_13",
      hash: "1873047_13",
      message:
        "Generate a valid Sampler object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/30b515db994b",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_14",
      hash: "1873047_14",
      message:
        "Generate a valid ShaderModule object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/6a97aed289ab",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_15",
      hash: "1873047_15",
      message:
        "Generate a valid ShaderModule object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/7142405fee57",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_16",
      hash: "1873047_16",
      message:
        "Generate a valid Texture object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/79282fd571c5",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_17",
      hash: "1873047_17",
      message:
        "Generate a valid Texture object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/8f0c15267535",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_18",
      hash: "1873047_18",
      message:
        "Generate a valid TextureView object on the JS side even if IPC is down. r=#webgpu-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/aca3db8439db",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_19",
      hash: "1873047_19",
      message:
        "Generate a valid TextureView object on the JS side even if IPC is down. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/bba7b8f2946f",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_20",
      hash: "1873047_20",
      message:
        "Move CommandEncoder and RenderBundleEncoder ::Finish to their respective file. r=#webgpu-reviewers",
      repository: "https://hg.mozilla.org/mozilla-central/rev/bc67106c19d8",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_21",
      hash: "1873047_21",
      message:
        "Move CommandEncoder and RenderBundleEncoder ::Finish to their respective file. r=webgpu-reviewers,ErichDonGubler",
      repository: "https://hg.mozilla.org/mozilla-central/rev/d0475e27ae48",
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_22",
      hash: "1873047_22",
      message: "Pushed by egubler@mozilla.com:",
      repository: null,
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1873047_23",
      hash: "1873047_23",
      message:
        "nical, since you are the author of the regressor, bug 1853140, could you take a look? Also, could you set the severity field?",
      repository: null,
      committed_at: null,
      bug_ids: ["1873047"],
    },
    {
      commit_id: "1872966_0",
      hash: "1872966_0",
      message:
        "there, the crashes appeared after test start test_youtube_flash_embed.html(which got disabled in that bug) , and now, here(and the other 2 bugs that I've added in the see also section) the crash happens afterTEST-START | dom/base/test/test_x-frame-options.html. I'm assuming that [this theory",
      repository: null,
      committed_at: null,
      bug_ids: ["1872966"],
    },
    {
      commit_id: "1872960_0",
      hash: "1872960_0",
      message: "Add a crash test for QM shutdown hangs.",
      repository: null,
      committed_at: null,
      bug_ids: ["1872960"],
    },
    {
      commit_id: "1872956_0",
      hash: "1872956_0",
      message:
        "Avoid copying document URI in nsLayoutUtils::PaintFrame unless logging.",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/68a7207fe026",
      committed_at: null,
      bug_ids: ["1872956"],
    },
    {
      commit_id: "1872956_1",
      hash: "1872956_1",
      message:
        "Avoid copying document URI in nsLayoutUtils::PaintFrame unless logging. r=layout-reviewers,tnikkel",
      repository: "https://hg.mozilla.org/mozilla-central/rev/68a7207fe026",
      committed_at: null,
      bug_ids: ["1872956"],
    },
    {
      commit_id: "1872956_2",
      hash: "1872956_2",
      message: "Pushed by aosmond@mozilla.com:",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/b2fb19537a38",
      committed_at: null,
      bug_ids: ["1872956"],
    },
    {
      commit_id: "1872834_0",
      hash: "1872834_0",
      message:
        "Add missing null check to FilePickerParent::RecvClose. r=canadahonk",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/036489e17b6c",
      committed_at: null,
      bug_ids: ["1872834"],
    },
    {
      commit_id: "1872834_1",
      hash: "1872834_1",
      message: "Pushed by choller@mozilla.com:",
      repository: "https://hg.mozilla.org/mozilla-central/rev/036489e17b6c",
      committed_at: null,
      bug_ids: ["1872834"],
    },
    {
      commit_id: "1872744_0",
      hash: "1872744_0",
      message: "Clean up DNSReqestSender::Cancel r=#necko-reviewers!",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/279a9187f4d0",
      committed_at: null,
      bug_ids: ["1872744"],
    },
    {
      commit_id: "1872744_1",
      hash: "1872744_1",
      message: "Clean up DNSReqestSender::Cancel r=necko-reviewers,valentin",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/293b7b46edece84b381ba4692fea53a089c93526",
      committed_at: null,
      bug_ids: ["1872744"],
    },
    {
      commit_id: "1872744_2",
      hash: "1872744_2",
      message: "Clean up DNSRequestSender::Cancel r=necko-reviewers,valentin",
      repository:
        "https://hg.mozilla.org/integration/autoland/rev/50eda61010c7",
      committed_at: null,
      bug_ids: ["1872744"],
    },
    {
      commit_id: "1872744_3",
      hash: "1872744_3",
      message: "Code cleanup r=valentin!",
      repository: "https://hg.mozilla.org/mozilla-central/rev/50eda61010c7",
      committed_at: null,
      bug_ids: ["1872744"],
    },
    {
      commit_id: "1872744_4",
      hash: "1872744_4",
      message: "Pushed by rjesup@mozilla.com:",
      repository:
        "https://hg.mozilla.org/releases/mozilla-beta/rev/09839b69bbd9",
      committed_at: null,
      bug_ids: ["1872744"],
    },
    {
      commit_id: "1872744_5",
      hash: "1872744_5",
      message:
        "[task 2024-09-06T20:43:25.637Z] 20:43:25 INFO - TEST-START | netwerk/test/unit/test_dns_cancel.js",
      repository:
        "https://hg.mozilla.org/releases/mozilla-esr115/rev/39e38fe9bbebf513460138ade3d23b67dc1c5f44",
      committed_at: null,
      bug_ids: ["1872744"],
    },
  ],
  edges: [
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_5",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873210",
      target_type: "commit",
      target_id: "1873210_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "commit",
      target_id: "1873801_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872956",
      target_type: "commit",
      target_id: "1872956_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_8",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_14",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872960",
      target_type: "commit",
      target_id: "1872960_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873577",
      target_type: "commit",
      target_id: "1873577_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "developer",
      target_id: "nical.bugzilla@gmail.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873210",
      target_type: "commit",
      target_id: "1873210_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873577",
      target_type: "developer",
      target_id: "jfkthame@gmail.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1872956",
      target_type: "commit",
      target_id: "1872956_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873661",
      target_type: "commit",
      target_id: "1873661_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_11",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_19",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_22",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873577",
      target_type: "commit",
      target_id: "1873577_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873874",
      target_type: "commit",
      target_id: "1873874_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_4",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873790",
      target_type: "commit",
      target_id: "1873790_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872966",
      target_type: "commit",
      target_id: "1872966_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_10",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873229",
      target_type: "commit",
      target_id: "1873229_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_6",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_18",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873210",
      target_type: "commit",
      target_id: "1873210_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872960",
      target_type: "developer",
      target_id: "nobody@mozilla.org",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1872966",
      target_type: "developer",
      target_id: "nobody@mozilla.org",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "developer",
      target_id: "rjesup@jesup.org",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873573",
      target_type: "commit",
      target_id: "1873573_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873573",
      target_type: "commit",
      target_id: "1873573_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873229",
      target_type: "commit",
      target_id: "1873229_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873661",
      target_type: "developer",
      target_id: "pmcmanis@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_23",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "commit",
      target_id: "1873801_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872956",
      target_type: "developer",
      target_id: "aosmond@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873790",
      target_type: "commit",
      target_id: "1873790_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_5",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_15",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873790",
      target_type: "developer",
      target_id: "aosmond@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1872744",
      target_type: "commit",
      target_id: "1872744_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_5",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873210",
      target_type: "commit",
      target_id: "1873210_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873701",
      target_type: "commit",
      target_id: "1873701_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873573",
      target_type: "developer",
      target_id: "echuang@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "developer",
      target_id: "aryx.bugmail@gmx-topmail.de",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873573",
      target_type: "commit",
      target_id: "1873573_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_4",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872834",
      target_type: "developer",
      target_id: "choller@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873229",
      target_type: "developer",
      target_id: "krosylight@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_13",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873661",
      target_type: "commit",
      target_id: "1873661_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873229",
      target_type: "commit",
      target_id: "1873229_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873577",
      target_type: "commit",
      target_id: "1873577_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_7",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872956",
      target_type: "commit",
      target_id: "1872956_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873229",
      target_type: "commit",
      target_id: "1873229_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873597",
      target_type: "developer",
      target_id: "bvandersloot@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_17",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_9",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_21",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873701",
      target_type: "commit",
      target_id: "1873701_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873874",
      target_type: "commit",
      target_id: "1873874_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872834",
      target_type: "commit",
      target_id: "1872834_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "commit",
      target_id: "1873801_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_12",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "developer",
      target_id: "docfaraday@gmail.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873597",
      target_type: "commit",
      target_id: "1873597_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873701",
      target_type: "developer",
      target_id: "aosmond@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873210",
      target_type: "developer",
      target_id: "afranchuk@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "commit",
      target_id: "1873801_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_20",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873801",
      target_type: "commit",
      target_id: "1873801_4",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873661",
      target_type: "commit",
      target_id: "1873661_1",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1872834",
      target_type: "commit",
      target_id: "1872834_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873790",
      target_type: "commit",
      target_id: "1873790_0",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873874",
      target_type: "commit",
      target_id: "1873874_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_16",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873577",
      target_type: "commit",
      target_id: "1873577_2",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873874",
      target_type: "developer",
      target_id: "omansfeld@mozilla.com",
      relation_type: "ASSIGNED_TO",
    },
    {
      source_type: "bug",
      source_id: "1873047",
      target_type: "commit",
      target_id: "1873047_3",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_4",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_7",
      relation_type: "FIXED_IN",
    },
    {
      source_type: "bug",
      source_id: "1873462",
      target_type: "commit",
      target_id: "1873462_6",
      relation_type: "FIXED_IN",
    },
  ],
};
